version: '3.5'

services:
  proxy_checker:
    image: deademo/proxy_checker
    command: "/proxy_checker/venv/bin/python /proxy_checker/proxy_checker/server.py"
    volumes: 
      - "./proxy_checker:/proxy_checker/proxy_checker"
    links:
      - mariadb
    ports:
      - "3300:3300"
  mariadb:
    image: mariadb
    volumes:
      - "./proxy_checker_data:/var/lib/mysql"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: proxy_checker
      MYSQL_ROOT_PASSWORD: toor
